### ISSUE TITLE
disperse readdata: in the "inpfile.dat", "degree of polymerization" works as "the number of residues" instead of "molecular weights"

### ISSUE THREAD

**Issue by PingpingJi** [vaidyanathanms/SPRInG_PolydispersePolymerBuilder#3]
Thanks so much for sharing this powerful and user-friendly code! 

Recently, when I tried to use "disperse READDATA inpfilename" to input the molecular weights (degree of polymerization) of all the chains, it seems like the numbers in the inpfile.dat were recognized as the number of residues but not the molecular weight of each chain. I am not sure if I use this keyword incorrectly because some misunderstanding. Following please kindly check an example of this issue:

              disperse READDATA Inpfile.dat

              <Inpfile.dat>
              num_chains 5
              410	
              1400	
              7900	
              11000	
              16000	
              
              The output step1.tcl gave us 5 chains obtain 410, 1400, 7900, 11000, 16000 residues.

#PS:
In the [README.md] of SPRInG,
>SPRInG Keywords
>>Keyword list
>>>5. disperse (Optional)
"READDATA reads a file containing the molecular weights (degree of polymerization) of all the chains from a file (see below for format)."

I would be very grateful if you could kindly teach me how to input the molecular weight of each chain.

**Comment by vaidyanathanms** [comment]
Hi,
I am really sorry I missed this for a long time. Inputting the Molecular Weight of each chain is not needed since polydispersity index draws a molecular weight distribution from a Schulz-Zimm distribution and assigns them directly.
